### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by minad** [Qkessler/consult-project-extra#1]
Hello @Qkessler!

Incidentally I just opened reddit and stumbled over your package. Thanks for creating this! I have one small favor to ask - could you please name your package differently to avoid future namespacing conflicts? Consult already uses the `consult-project` namespace, e.g., `consult-project-root-function`, and I may also extend usage of the namespace and add project sources to Consult itself. See the issue https://github.com/minad/consult/issues/315, which proposed different project sources earlier. I haven't done this yet since sources like the project file source can be quite slow for large projects. If you have the FSF copyright assignment (or if you are willing to get it), we could even reuse code from here. However there is also a bit of a chain, since this project is based on consult-projectile? Anyways, first I also have to think again about the performance implications and potential solutions. Regarding the name I don't have a good proposal yet. Maybe you have a good idea? The name project.el is intentionally generic, since it is part of Emacs itself. This makes it a bit hard to find something else.

**Comment by minad** [comment]
One source I could adopt right away in Consult is `consult--source-project` which provides a list of all known projects. This source doesn't lead to issues since it doesn't return an excessive amount of candidates. The only truly problematic source is the file source. What do you think?

**Comment by Qkessler** [comment]
Hi Daniel!
Thank you for the feeback! I have no trouble at all changing the name. The only problem is what you mention, project is specially generic, and we might need a bit of time to come up with something of value!
Regarding the FSF copyright agreement, I don't really understand what you mean. I thought the GNU v3 license was enough? Would you mind explaining further?
Second to last, sure! let's adopt the project source! What would the problem be with the file source? There might be a lot of candidates, but for this specific use-case that is what you expect? Is the file source (a.k.a the project-file function) too inefficient? I'm using this project to improve my elisp and I still don't have the grasp of efficiency of certain aspects of it.
Lastly, thanks again! I really appreciate the service you are giving the community. Keep it up!
Best,
Enrique.

**Comment by minad** [comment]
> Regarding the FSF copyright agreement, I don't really understand what you mean. I thought the GNU v3 license was enough? Would you mind explaining further?

Consult is distributed via GNU ELPA under the same license conditions as Emacs itself. Therefore copyright is assigned to the FSF. For example the modus themes have the same conditions, see here: https://protesilaos.com/emacs/modus-themes#h:111773e2-f26f-4b68-8c4f-9794ca6b9633

> Second to last, sure! let's adopt the project source! 

Okay, I will add this soon. I will probably call it `consult--source-project-roots`.

> Is the file source (a.k.a the project-file function) too inefficient? 

Yes, this is the problem. Since `consult-buffer` is used as buffer switcher drop-in it must be fast. We cannot wait for project.el to search through the project folder and find all files. However project.el may have good caching which makes this less of an issue.

> Lastly, thanks again! I really appreciate the service you are giving the community. Keep it up!

Thanks!

> Thank you for the feeback! I have no trouble at all changing the name. The only problem is what you mention, project is specially generic, and we might need a bit of time to come up with something of value!

That's good to hear. I should probably clarify a bit further. So the problem is not so much if our two packages use a common namespace `consult-project-*`. We could fix conflicts on a case-by-case basis. It would be tedious but not a big issue. The bigger issue is, if you distribute a file consult-project.el and I add a consult-project.el file at some point to Consult. This may or may not happen. But in that case, our packages would be in conflict and Emacs wouldn't know which package to load.

**Comment by Qkessler** [comment]
> Consult is distributed via GNU ELPA under the same license conditions as Emacs itself. Therefore copyright is assigned to the FSF. For example the modus themes have the same conditions, see here: https://protesilaos.com/emacs/modus-themes#h:111773e2-f26f-4b68-8c4f-9794ca6b9633

Sure, I'll work on that. Doesn't seem all that hard. EDIT: Already sent the email.

> Yes, this is the problem. Since consult-buffer is used as buffer switcher drop-in it must be fast. We cannot wait for project.el to search through the project folder and find all files. However project.el may have good caching which makes this less of an issue. 

What do you propose? I see that you have been keeping an eye on project.el, when I last built master.

> That's good to hear. I should probably clarify a bit further. So the problem is not so much if our two packages use a common namespace consult-project-*. We could fix conflicts on a case-by-case basis. It would be tedious but not a big issue. The bigger issue is, if you distribute a file consult-project.el and I add a consult-project.el file at some point to Consult. This may or may not happen. But in that case, our packages would be in conflict and Emacs wouldn't know which package to load.

Alright, let's make that name change happen.

Best,
Enrique.

**Comment by minad** [comment]
> What do you propose? I see that you have been keeping an eye on project.el, when I last built master.

I don't have a concrete plan. I have to think about this more. For now I introduced the `consult--source-project-root` and a generalized `consult-project-function`, see https://github.com/minad/consult/commit/68cc5895f5cf915f83e423275633c6872c9074f8.

**Comment by Qkessler** [comment]
Great to see! About the name, what do you think about consult-project-view or consult-pmsv (project-multi-source-view)?

**Comment by minad** [comment]
consult-project-view sounds nice. Other alternatives:

- consult-proj
- consult-project-el
- consult-switch-project
- consult-jump-project
- consult-project-select
- consult-project-sources
- consult-project-src

**Comment by Qkessler** [comment]
consult-proj sounds better I think, shorter names on the functions 
and variables always seem nicer.

Thanks again, Daniel!

Best,

On 2022-02-15, 07:58 -0800, Daniel Mendler 
***@***.***> wrote:

> consult-project-view sounds nice. Other alternatives:
>
> * consult-proj
> * consult-project-el
> * consult-switch-project
> * consult-jump-project
> * consult-project-select
> * consult-project-sources
> * consult-project-src
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.


-- 
Enrique Kessler Martínez

**Comment by minad** [comment]
Okay good! Thanks for making the change. I am sorry for the inconvenience but I think it is better to treat some of the `consult-<generic>-*` namespaces as reserved such that we can potentially move stuff directly into Consult. We will see how things develop. If you have improvement proposals, please let me know! :)

**Comment by Qkessler** [comment]
Sure, thanks for the discussion! :smile:

**Comment by minad** [comment]
One small correction to your reddit post:

> On the other side, consult by default does not implement a view to access project buffers, project files and other known projects, which is what this package attempts to do.

Consult implements access to project buffers and known projects in `consult-buffer`, only files are not available. There is `consult--source-project-recent-file` however, which admittedly is a poor substitute. And well, there is no `consult-project` command which combines these sources.

A possible plan for adding the functionality to Consult could be like this:

- Add a `consult--source-project-file`, which will be slow. That's okay as long as it is not used by `consult-buffer`.
- Add a consult-project command which combines `consult--source-project-file`, `consult--source-project-buffer`, `consult--source-project-root`.

Another improvement, which I've considered for a while now is, to change change consult--multi such that it populates :hidden sources lazily. Then one could even use the source in consult-buffer as long as it is hidden by default. Another idea would be to introduce more aggressive caching, since `project--files-in-directory` always shells out to `find`. It is kind of a bad idea to always call find when switching buffers. :)

One thing I should emphasize - I don't want to take this package away from you. It just happens that Consult has been a bit lacking on the project front and you are pushing me to improve that. In general I try to avoid stuffing more and more functionality into Consult to keep the size of Consult somehow in check. Still, the project part is a generic thing which would be nice to have. I hope this doesn't diminish your motivation to create new Emacs packages!

**Comment by Qkessler** [comment]
> A possible plan for adding the functionality to Consult could be like this:
> 
> Add a consult--source-project-file, which will be slow. That's okay as long as it is not used by consult-buffer.
> Add a consult-project command which combines consult--source-project-file, consult--source-project-buffer, consult--source-project-root.

> One thing I should emphasize - I don't want to take this package away from you. It just happens that Consult has been a bit lacking on the project front and you are pushing me to improve that. In general I try to avoid stuffing more and more functionality into Consult to keep the size of Consult somehow in check. Still, the project part is a generic thing which would be nice to have. I hope this doesn't diminish your motivation to create new Emacs packages!

I'm more than happy for this project to be absorbed by Consult, I also find that project management is a generic enough task for it to be supported by consult. 

> Another improvement, which I've considered for a while now is, to change change consult--multi such that it populates :hidden sources lazily. Then one could even use the source in consult-buffer as long as it is hidden by default. Another idea would be to introduce more aggressive caching, since project--files-in-directory always shells out to find. It is kind of a bad idea to always call find when switching buffers. :)

This would be in my opinion the path to take. Maybe also contributing to project.el to improve that caching could also be on the roadmap. Let's all profit from a great built-in package!

**Comment by minad** [comment]
Okay, for now I've added the `consult-project-buffer` command, which is just a simple wrapper around `consult-buffer`. See https://github.com/minad/consult/commit/2ee72ed487063d201d3936bf65e8f2e36e71a9e9. Maybe that's all I will add to Consult with regards to project support. 

I have an idea - what about calling your project `consult-project-extra`? I think that would be the best name and it would make it clear that you provide extra additions in comparison to the more basic Consult project support. We could still gradually move things from here to Consult. But when I look at `C-x p C-h` there are many things there, so maybe you will add more advanced consultified commands here? In contrast, `consult-proj` is a bit unclear, since it doesn't tell what this is about. What do you think?

**Comment by minad** [comment]
Also on reddit there are many comments about workspaces etc. All these things seem out of scope for Consult, so maybe these would fit into `consult-project-extra`?

**Comment by Qkessler** [comment]
> I have an idea - what about calling your project consult-project-extra? I think that would be the best name and it would make it clear that you provide extra additions in comparison to the more basic Consult project support. We could still gradually move things from here to Consult. But when I look at C-x p C-h there are many things there, so maybe you will add more advanced consultified commands here? In contrast, consult-proj is a bit unclear, since it doesn't tell what this is about. What do you think?

I think it's a good idea. I'll change the name. I also agree with you that the scope of this project seemed initially rather reduced. Integrating some of the project commands with the consult boost seems good development. Workspaces are not out of the question. There are different options that come to mind.

**Comment by minad** [comment]
Yes. So the plan for Consult is now to keep it more restricted. `consult-project-buffer` makes a lot of sense, since it is just a restricted `consult-buffer`. In order to make a file available there it must be in the recent file list, so should be opened first via `project-find-file`. This ensures that `consult-buffer` and `consult-project-buffer` are always fast. All other integrations could go to your package, file finder, workspaces, etc.

**Comment by minad** [comment]
Okay, another update: I removed `consult--source-project-root` again and went back to the simpler `consult-project-root-function`, see https://github.com/minad/consult/commit/94224d0f91c6eddb073c812805ea3f7eaf7ed458. So we are back to a smaller scope, the only new addition is `consult-project-buffer`. Note that your `consult-project-extra` can also add to `consult-project-buffer-sources`.

**Comment by Qkessler** [comment]
Learning: would you mind giving me some insight on the change? 
What motivated you to revert the changes?
Thanks for the information Daniel,

On 2022-02-15, 11:08 -0800, Daniel Mendler 
***@***.***> wrote:

> Okay, another update: I removed consult--source-project-root 
> again and went back
> to the simpler consult-project-root-function, see 
> ***@***.*** So we
> are back to a smaller scope, the only new addition is 
> consult-project-buffer.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.


-- 
Enrique Kessler Martínez

**Comment by minad** [comment]
When thinking about this issue it became more clear to me where to draw the proper line between basic Consult project support and consult-project-extra. I went back to the Consult version where I use only a simpler consult-project-root-function. New additions are the consult-project-buffer command (drop-in for project-switch-to-buffer) and the new default setting of the consult-project-root-function. Furthermore the consult-project-root-function has the ability to query the user for a project now.

Extending the consult-project-root-function to a function which makes it possible to query more information (all known projects, files of current project) muddies the separation between your package and Consult and leads to complications. Consult limits itself to project support which can be performed with a single piece of information, the project directory and nothing else. Having only this information is surprisingly effective and takes us a long way.

Other sources like a list of all project files or a list of all projects can live well inside your project. For basic Consult I don't think having a consult--source-project-root source is really necessary and doesn't justify the move to a new consult-project-function. We can still reconsider this later on. But for now it seems better to me to collect such more special functionality outside of Consult. What do you think?

**Comment by minad** [comment]
Also there seem to be multiple projects popping up right now, which may also go into the space of project/perspective management:

* Maybe your consult-project-extra
* https://github.com/mclear-tools/emacs-workspaces
* https://github.com/fritzgrabo/project-tab-groups

I think it makes sense to explore this space in other packages outside of Consult. If I would move to a general API which allows me to query all kinds of project information, it is much less clear where to draw the line. I value a modular ecosystem highly. Consult itself is maybe a bit guilty of not being as modular as it could be.
