### ISSUE TITLE
Project files by recency

### ISSUE THREAD

**Issue by sonofjon** [Qkessler/consult-project-extra#10]
How do I make `consult-project-extra-find` present files sorted by recency? 

I have `recentf-mode` active and `find-file` shows files sorted by recency as expected, but `consult-project-extra-find` does not.

**Comment by Qkessler** [comment]
Hi there!

We are building the project-file source directly from the files that the function `project-find-file` gives. I don't believe there is a way currently to do it, AFAIK.

Please, correct me if I'm wrong, and if you find it, feel free to open a PR changing the README with that info!

Best,
Quique.
