### ISSUE TITLE
Performance on large projects

### ISSUE THREAD

**Issue by shartf** [Qkessler/consult-project-extra#12]
Hi, 
I've added a project with over 68k files and noticed that popping up consult-project-extra--project-files takes several seconds. My elisp is bad, but I was able to speed it up with following code using ripgrep, which seems to work and opens suggestions under a second on my machine:

``` elisp
(defun consult-project-extra--project-files (root)
"Compute the project files given the ROOT."
(let* ((project (consult-project-extra--project-with-root root))
(default-directory root)
(files (split-string (shell-command-to-string "rg --files --no-messages") "\n" t)))
(mapcar #'identity files)))
```

As a general question: would it maybe make sense to provide a feature-switch for ripgrep in the package so that people who have it installed can profit from it? The performance difference in negligible in small project, but day and night on big ones. 

Best regards and thank you for the package!

**Comment by Qkessler** [comment]
I'm hesitant to diverge from the current implementation using `project`'s APIs. Today, we use directly `project-find-file`, so I wonder whether the speed-up should come from there. Specially, considering `rg` is an option (one I use myself as well), there may be other binaries that people are interested in using, depending on the platform.

**Comment by shartf** [comment]
Thanks, 

that is fair enough, I am satisfied with the current local workaround. I will close the issue then.

**Comment by Qkessler** [comment]
Thanks for the workaround! Happy to take a PR if you are interested in contributing adding a section on the README to troubleshoot latency issues!

**Comment by shartf** [comment]
I will write it down properly the days and make a PR with with additional section in the README
