### ISSUE TITLE
Differences from normal consult-buffer with project narrowing?

### ISSUE THREAD

**Issue by jdtsmith** [Qkessler/consult-project-extra#6]
So consult-buffer includes a `p` narrowing key to narrow to project files, as defined by project.el. I have the feeling that got added afterward this package was created (possibly inspired by it).  

Is the main difference here that yours also includes "known" projects to select among, and that buffers for the project are also separated out?

**Comment by Qkessler** [comment]
Hi there! I would say when I created this package I wanted a way to move fast between the files and buffers associated with my known projects. It's fair to say that consult-buffer (with the "p" narrowing) already includes known projects. 

Using consult-project-extra-find you get the list of files and buffers associated with the project you select, which I find valuable! 

Do you have any feedback on the package or do you maybe have a different use case than mine?
Best,
Enrique.

**Comment by jdtsmith** [comment]
Thanks.  I'm wondering whether it might be convenient to extend `consult-buffer` itself, instead of having to choose a separate command in advance.  At present `consult-buffer` enables:

![image](https://user-images.githubusercontent.com/93749/163593399-415a8afa-424a-42b4-be44-1c30849eb569.png)

The idea would be that, if coming from a file from a known project, `consult-buffer` could simply present a separate `B project-buffers` to go with `p Project` (which should probably be renamed `p Project Files` in the above interface, as it does _not_ include open buffers affiliated with a project).  It might be nice to display that project in the prompt too, e.g. `[myproj] Switch to : `.

`P projects` could always be present, and do the same thing as consult-project-extra already does (prompt for a project file in that project).    Basically this would save the overhead of having to decide in advance "I'm interesting only in projects or project buffers/files".  

Thanks for the package.

**Comment by jdtsmith** [comment]
Sorry please ignore that, I had a mis-compiled consult, leading to some oddities.  Once corrected, consult now gives me project buffers AND files under `?p` — perfect.  

So adding to the default consult-buffer sources `P projects` would be enough for me.  I may just borrow your implementation and sneak that into my config.

**Comment by jdtsmith** [comment]
I put together a [little example](https://github.com/minad/consult/issues/6#issuecomment-1100566254) of the interface ideas I had, as a standalone call to consult-buffer with some logic.  As mentioned there, the only real difference is that mine displays the list of other projects all the time using the same interface.  So "switching" to another project happens the exact same way, whether starting from a project or not, and the process of switching simply re-launches the tool.  Give it a try if interested.

**Comment by Qkessler** [comment]
Thanks for closing!

**Comment by jdtsmith** [comment]
Thanks for the good ideas.  If you want to see what I came up with, check https://github.com/jdtsmith/consult-jump-project.  Sounds like @minad has thought about adding a custom marginalia `project-root` category, but still needs to think about it more.

**Comment by minad** [comment]
I think it is okay to add a project-root category if we get a special marginalia-annotate-project-root annotator.
