### ISSUE TITLE
use project-ignore-buffer-conditions

### ISSUE THREAD

**Issue by Dickby** [Qkessler/consult-project-extra#7]
because Minad has correctly not accepted this for consult-project-buffer because that is not tight to project.el,
i try it here. I think because this is using project.el it should also ignore the buffers that are ignored by project-ignore-buffer-conditions

**Comment by Qkessler** [comment]
Hi there, thanks for trying the package! Nevertheless, I don't think an issue should be open, as there isn't really a question on it! 

Thanks!
Quique.

**Comment by Dickby** [comment]
project.el has a variable `project-ignore-buffer-conditions` .
Because your package is extending the functionality of project.el, the buffers that are ignored by project.el should be excluded from the buffers listed by
`consult-project-extra-find`
