### ISSUE TITLE
Hidden path is included in filtered result

### ISSUE THREAD

**Issue by lynnux** [Qkessler/consult-project-extra#8]
Although project root path is hidden on the completion list, but when change candidate, it's still affect filter, thus cause a bit confuse.
Like this gif, the project root is `c:\green\emacs\.emacs.d`, if you type `emacs`, it can't filter the file name who contains `emacs`, but show all the files in project.
![22](https://user-images.githubusercontent.com/367894/172986659-15e22aab-5596-41f3-a2e4-e61622e264b7.gif)

Another gif is use `consult-project-buffer`:
![22](https://user-images.githubusercontent.com/367894/172987336-ccbae892-ed80-47b8-bf1e-05b3932ba829.gif)

**Comment by lynnux** [comment]
This can only be reproduced when `default-directory` is the project root directory.
my minimal setting:
```
(eval-when-compile
  (add-to-list 'load-path "~/.emacs.d/packages/use-package")
  (require 'use-package))

(add-to-list 'load-path
	     "~/.emacs.d/packages")
(use-package vertico
           :load-path "~/.emacs.d/packages/minibuffer/vertico-main"
           :init
           :config
           (vertico-mode 1)
           )

(add-to-list 'load-path "~/.emacs.d/packages/minibuffer")
(use-package orderless
             :config
             (setq completion-styles '(orderless basic)))

(use-package consult
           :load-path "~/.emacs.d/packages/minibuffer/consult-main"
           :init

           ;; https://github.com/phikal/compat.el
           (use-package compat
             :defer t
             :load-path "~/.emacs.d/packages/minibuffer/compat.el-master"
             )
           
           (use-package consult-project-extra
             :commands(consult-project-extra-find))
           :config
 )

```

**Comment by Qkessler** [comment]
Thank you for flagging! I don't have the bandwidth to look into it now, but I encourage you to submit a PR if you have a solution! 

Quique.

**Comment by Qkessler** [comment]
Hi @lynnux, got the time to come around and fix this issue! 

Please, do some testing on the main branch (should get published to Melpa soon), to ensure that all the cases are covered.

Thank you for flagging again, great reproducible example.
Best,
Quique.

**Comment by lynnux** [comment]
Thank you @Qkessler , the bug is fixed, I'v tested all the cases above, they all work good!
